#! /bin/sh


# Autostart
nvidia-settings --load-config-only &
nitrogen --restore &

pgrep -x pipewire > /dev/null || pipewire & 
pgrep -x sxhkd    > /dev/null || sxhkd &
pgrep -x picom    > /dev/null || picom &
pgrep -x mpd      > /dev/null || mpd &
pgrep -x polybar  > /dev/null || polybar &

xcape -e "Super_L=Alt_L|F1" &
xset r rate 250 25 &
xset m 0 0 &
xsetroot -cursor_name left_ptr &

XDG_SESSION_TYPE=x11 plank &

# Workspaces
bspc monitor -d 1 2 3 4 5 6 7

# Windows
bspc config border_width           2
bspc config window_gap             12

bspc config normal_border_color   "#181926"
bspc config active_border_color   "#cad3f5"
bspc config focused_border_color  "#cad3f5"
bspc config presel_feedback_color "#cad3f5"

bspc config split_ratio            0.5
bspc config borderless_monocle     true
bspc config gapless_monocle        true

bspc subscribe node_add | while read -r _; do
   xdo raise -N Plank
done &
